/**
 * Workout Plan Types
 * These types define the structure of workout plans generated by the multi-agent system.
 * Keep in sync with backend agent outputs.
 */

// Workout phases
export type WorkoutPhase = "warmup" | "workout" | "cooldown" | "rest" | "completed";

// Quit reasons for feedback
export type QuitReason =
  | "dont_know_how"
  | "too_easy"
  | "too_hard"
  | "just_looking"
  | "no_time"
  | "other";

// Individual exercise in a workout plan
export interface WorkoutExercise {
  exercise_id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  work_duration_seconds: number;
  rest_between_sets_seconds: number;
  target_muscle: string;
  focus_cues: string[];
  // Timer vs rep-based display
  is_timed: boolean; // true = countdown timer, false = "Do X reps" + Done button
  // Demo data (added by backend)
  demo?: ExerciseDemo;
  // Optional additional fields
  duration?: string;
  mp4_url?: string;
  instructions?: string[];
}

// Exercise demo data (from database)
export interface ExerciseDemo {
  id: string;
  mp4_url: string;
  target_muscle: string;
  body_part?: string;
  equipment?: string;
  difficulty?: string;
  secondary_muscles?: string[];
  instructions?: string[];
  description?: string;
  category?: string;
}

// Warm-up/Cool-down exercise (simpler structure)
export interface WarmupCooldownExercise {
  exercise_id?: string;
  name: string;
  duration_seconds: number;
  is_timed: boolean; // Warmup/cooldown are always timed
  side?: "each" | "both";
  description?: string;
  instructions_summary?: string;
  type?: "warmup" | "cooldown" | "dynamic" | "static_stretch";
  target_muscle?: string;
  mp4_url?: string;
  instructions?: string[];
}

// Warm-up section
export interface WarmupSection {
  duration_seconds?: number;
  description?: string;
  exercises: WarmupCooldownExercise[];
}

// Main workout section
export interface MainWorkoutSection {
  rest_between_exercises_seconds?: number;
  exercises: WorkoutExercise[];
  style?: "traditional" | "circuit" | "superset";
}

// Cool-down section
export interface CooldownSection {
  duration_seconds?: number;
  description?: string;
  exercises: WarmupCooldownExercise[];
}

// Weekly progression adjustment (flexible to accept API and internal formats)
export interface WeeklyAdjustment {
  week: number;
  intensity?: string;
  focus?: string;
  reps_modifier?: number;
  sets_modifier?: number;
  rest_modifier?: number;
  notes?: string;
}

// Progression schedule (flexible to accept API format)
export interface ProgressionSchedule {
  current_week?: number;
  weekly_focus?: string;
  weekly_adjustments?: WeeklyAdjustment[];
  // Multi-agent system also includes these
  goal_type?: "habit" | "time_challenge" | "target_challenge";
  streak_milestones?: Array<{
    days: number;
    title: string;
    description?: string;
  }>;
}

// Complete workout structure
export interface WorkoutStructure {
  total_duration_minutes?: number;
  warm_up?: WarmupSection;
  main_workout?: MainWorkoutSection;
  cool_down?: CooldownSection;
  progression?: ProgressionSchedule;
  // Legacy/fallback - for older plan formats
  routine?: MainWorkoutSection;
}

// Guidance section
export interface WorkoutGuidance {
  description?: string;
  tips?: string[];
  safety_notes?: string[];
}

// Complete workout plan (structured_data in actionable_plans)
export interface WorkoutPlan {
  plan_type?: string; // "workout_plan" | "routine" | "habit_plan" (flexible for backend)
  structure?: WorkoutStructure;
  guidance?: WorkoutGuidance;
}

// For backward compatibility - the routine structure (older format)
export interface RoutineStructure {
  exercises: WorkoutExercise[];
  rest_between_exercises_seconds?: number;
}

// ==========================================
// Workout Session Types (for progress persistence)
// ==========================================

// Session status
export type SessionStatus = "in_progress" | "completed";

// Workout session (from API)
export interface WorkoutSession {
  id: string;
  user_id: string;
  goal_id: string | null;
  plan_id: string | null;
  started_at: string;
  completed_at: string | null;
  paused_duration_seconds: number;
  total_duration_seconds: number | null;
  exercises_completed: number;
  exercises_total: number;
  exercises_skipped: number;
  sets_completed: number;
  sets_total: number;
  workout_data: Record<string, any>;
  status: SessionStatus;
  created_at: string;
  // Progress tracking fields
  current_phase: WorkoutPhase;
  current_exercise_index: number;
  current_set: number;
  current_round: number;
  completion_percentage: number;
  paused_at: string | null;
  // Practice mode and enhanced tracking
  is_practice_session?: boolean;
  actual_exercise_time_seconds?: number;
  calories_burned?: number;
  feedback_rating?: "hard" | "just_right" | "easy" | null;
}

// Active session response from API
export interface ActiveSessionResponse {
  session: WorkoutSession | null;
  can_resume: boolean;
  completion_percentage?: number;
  current_phase?: WorkoutPhase;
  current_exercise_index?: number;
}

// Save progress request
export interface SaveProgressRequest {
  current_phase: WorkoutPhase;
  current_exercise_index: number;
  current_set: number;
  current_round: number;
  completion_percentage: number;
  exercises_completed: number;
  sets_completed: number;
  paused_duration_seconds: number;
  workout_data?: Record<string, any>;
}

// Submit feedback request
export interface SubmitFeedbackRequest {
  session_id?: string;
  goal_id?: string; // For goal-based workouts
  challenge_id?: string; // For standalone challenge workouts
  plan_id?: string;
  quit_reason: QuitReason;
  additional_feedback?: string;
  exercises_completed: number;
  completion_percentage: number;
  time_spent_seconds: number;
  current_exercise_name?: string; // Name of exercise user was on when they quit (helps AI)
}

// Workout stats from API
export interface WorkoutStats {
  total_workouts: number;
  total_duration_minutes: number;
  total_exercises: number;
  total_sets: number;
  average_duration_minutes: number;
  completion_rate: number;
  current_streak: number;
}

// Timer state for workout player
export interface WorkoutTimerState {
  phase: WorkoutPhase;
  currentExerciseIndex: number;
  currentSetIndex: number;
  currentRound: number;
  timeRemaining: number;
  totalTime: number;
  isPlaying: boolean;
  isPaused: boolean;
  progress: number; // 0-100
}
