"""
FitNudge V2 - Motivation Service

Handles AI generation for:
1. Daily Motivations (MotivationCard - morning message)
2. Check-in Responses (after user completes check-in)

Strategy:
- FREE users: Template-based responses (no API cost)
- PREMIUM users: Full GPT-generated personalized responses

Daily motivations are generated by Celery scheduler each morning.
Check-in responses are generated:
- Immediately for FREE users (template)
- In background for PREMIUM users (async AI)
"""

from typing import Optional, List
from openai import AsyncOpenAI
from app.core.config import settings
from app.services.logger import logger
import random


# Initialize OpenAI client
client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)


# =============================================================================
# BACKGROUND STYLE → COLOR MAPPING
# =============================================================================

BACKGROUND_COLORS = {
    "gradient_sunset": ["#FF9A9E", "#FECFEF", "#FECFEF"],
    "gradient_mountain": ["#E0C3FC", "#C8A8FF", "#9B7BFF"],
    "gradient_ocean": ["#667EEA", "#764BA2", "#667EEA"],
    "gradient_forest": ["#84FAB0", "#8FD3F4", "#84FAB0"],
    "gradient_purple": ["#A8EDEA", "#FED6E3", "#D299C2"],
    "gradient_pink": ["#FFECD2", "#FCB69F", "#FF9A9E"],
    "gradient_fire": ["#F83600", "#FE8C00", "#F83600"],
    "gradient_ice": ["#00C9FF", "#92FE9D", "#00C9FF"],
}


# =============================================================================
# TEMPLATE RESPONSES (No AI cost)
# =============================================================================


def get_template_response(
    user_name: str,
    completed: bool,
    is_rest_day: bool = False,
    current_streak: int = 0,
    motivation_style: str = "supportive",
) -> str:
    """
    Get a template-based response for FREE users.
    No API call needed - instant response.
    """
    if is_rest_day:
        return _get_rest_day_templates(user_name, motivation_style)

    if completed:
        return _get_completed_templates(user_name, current_streak, motivation_style)
    else:
        return _get_missed_templates(user_name, motivation_style)


def _get_rest_day_templates(user_name: str, style: str) -> str:
    """Templates for rest days."""
    templates = {
        "supportive": [
            f"Rest well, {user_name}! Recovery is part of the journey. 🧘",
            f"Smart choice, {user_name}. Your body will thank you tomorrow!",
            f"Enjoy your rest, {user_name}! You've earned it.",
        ],
        "tough_love": [
            f"Smart move, {user_name}. Rest today, dominate tomorrow.",
            f"Rest up. Winners know when to recover, {user_name}.",
            f"Good call, {user_name}. Even champions need rest days.",
        ],
        "calm": [
            f"Rest is not idleness, {user_name}. It's preparation for what's next.",
            f"A day of rest, a step toward balance, {user_name}.",
            f"Honor your body's need for recovery today, {user_name}.",
        ],
    }
    return random.choice(templates.get(style, templates["supportive"]))


def _get_completed_templates(user_name: str, streak: int, style: str) -> str:
    """Templates for completed check-ins based on streak."""
    if streak >= 30:
        templates = {
            "supportive": [
                f"Incredible, {user_name}! {streak} days! You're unstoppable! 🔥",
                f"LEGEND status, {user_name}! {streak} days strong! 👏",
                f"WOW! {streak} days, {user_name}! You're rewriting your story!",
            ],
            "tough_love": [
                f"{streak} days, {user_name}. This is who you are now. Keep pushing.",
                f"You've earned {streak} days. Don't you dare stop now, {user_name}.",
                f"{streak} days of proof, {user_name}. You're built different.",
            ],
            "calm": [
                f"Day {streak}, {user_name}. Consistency has become your nature.",
                f"{streak} days of quiet discipline. Remarkable, {user_name}.",
                f"The person who started on day 1 would be proud, {user_name}.",
            ],
        }
    elif streak >= 14:
        templates = {
            "supportive": [
                f"Two weeks strong, {user_name}! {streak} days and counting! 💪",
                f"You're on fire! {streak} days of pure dedication, {user_name}!",
                f"This is becoming a habit, {user_name}! Keep it up! 🌟",
            ],
            "tough_love": [
                f"{streak} days. You're proving you mean business, {user_name}.",
                f"Nice streak, {user_name}. Now let's see {streak + 7} more days.",
                f"Getting comfortable? Good. But don't slow down, {user_name}.",
            ],
            "calm": [
                f"Day {streak}. The habit is taking root, {user_name}.",
                f"{streak} days of steady progress. Well done, {user_name}.",
                f"Patience and persistence. Day {streak}, {user_name}.",
            ],
        }
    elif streak >= 7:
        templates = {
            "supportive": [
                f"A whole week, {user_name}! {streak} days! Amazing! 🎉",
                f"You're building momentum! {streak} days strong! ⭐",
                f"Look at you go, {user_name}! {streak} days! Keep shining!",
            ],
            "tough_love": [
                f"Good, {user_name}. {streak} days down. Now don't get comfortable.",
                f"{streak} days. The real test is what comes next, {user_name}.",
                f"Solid week, {user_name}. But one week doesn't define you.",
            ],
            "calm": [
                f"A week complete, {user_name}. One step at a time.",
                f"Day {streak}. The journey continues, {user_name}.",
                f"Another day, another step forward. Day {streak}, {user_name}.",
            ],
        }
    elif streak >= 3:
        templates = {
            "supportive": [
                f"Yes! {streak} days in a row, {user_name}! The momentum is building! 💪",
                f"You're doing it, {user_name}! {streak} days and counting!",
                f"Three days proves it's not luck, {user_name}! Keep going!",
            ],
            "tough_love": [
                f"Day {streak}, {user_name}. Not bad. Now prove it wasn't a fluke.",
                f"{streak} days is a start. Keep your foot on the gas, {user_name}.",
                f"Done. {streak} days. Let's make it {streak + 4}, {user_name}.",
            ],
            "calm": [
                f"Day {streak}, {user_name}. Small steps, big changes.",
                f"{streak} days of showing up. That matters, {user_name}.",
                f"Consistency begins here, {user_name}. Day {streak}.",
            ],
        }
    else:
        templates = {
            "supportive": [
                f"Well done, {user_name}! Every step forward counts! ✨",
                f"You showed up today, {user_name}! That's what matters! 🙌",
                f"Great job, {user_name}! Keep building that momentum!",
            ],
            "tough_love": [
                f"Done. That's what matters, {user_name}. Now do it again tomorrow.",
                f"Good, {user_name}. One down. Let's stack another one tomorrow.",
                f"You did it. Simple as that. Now keep going, {user_name}.",
            ],
            "calm": [
                f"One step at a time, {user_name}. Today you moved forward.",
                f"Another day complete, {user_name}. Progress is quiet.",
                f"Well done, {user_name}. The path is walked one day at a time.",
            ],
        }

    return random.choice(templates.get(style, templates["supportive"]))


def _get_missed_templates(user_name: str, style: str) -> str:
    """Templates for missed check-ins."""
    templates = {
        "supportive": [
            f"It's okay, {user_name}. Tomorrow is a new chance. 💙",
            f"One day doesn't define you, {user_name}. Keep going!",
            f"Rest if you need to, {user_name}. Your journey continues tomorrow.",
        ],
        "tough_love": [
            f"Missed today, {user_name}. It happens. But don't make it a habit.",
            f"Okay, you missed. Now what? Get back at it tomorrow, {user_name}.",
            f"One miss won't break you, {user_name}. Letting it become two will.",
        ],
        "calm": [
            f"A pause, not an ending, {user_name}. The path is still there.",
            f"Today was rest. Tomorrow is opportunity, {user_name}.",
            f"Even the strongest streams find still moments, {user_name}.",
        ],
    }
    return random.choice(templates.get(style, templates["supportive"]))


# =============================================================================
# AI-GENERATED RESPONSES (Premium only)
# =============================================================================


async def generate_checkin_motivation(
    user_name: str,
    goal_title: str,
    completed: bool,
    is_rest_day: bool = False,
    mood: Optional[str] = None,
    skip_reason: Optional[str] = None,
    current_streak: int = 0,
    longest_streak: int = 0,
    why_statement: Optional[str] = None,
    motivation_style: str = "supportive",
    is_premium: bool = False,
) -> str:
    """
    Generate AI response after a check-in.

    For FREE users: Returns template-based response (no API call)
    For PREMIUM users: Full GPT-generated personalized response
    """
    # FREE USERS: Template-based responses (no AI cost)
    if not is_premium:
        return get_template_response(
            user_name=user_name,
            completed=completed,
            is_rest_day=is_rest_day,
            current_streak=current_streak,
            motivation_style=motivation_style,
        )

    # PREMIUM USERS: Full AI-generated response
    return await _generate_ai_checkin_response(
        user_name=user_name,
        goal_title=goal_title,
        completed=completed,
        is_rest_day=is_rest_day,
        mood=mood,
        skip_reason=skip_reason,
        current_streak=current_streak,
        longest_streak=longest_streak,
        why_statement=why_statement,
        motivation_style=motivation_style,
    )


async def _generate_ai_checkin_response(
    user_name: str,
    goal_title: str,
    completed: bool,
    is_rest_day: bool,
    mood: Optional[str],
    skip_reason: Optional[str],
    current_streak: int,
    longest_streak: int,
    why_statement: Optional[str],
    motivation_style: str,
) -> str:
    """Full AI-generated response for premium users."""
    # Build outcome context
    if is_rest_day:
        outcome = "took a rest day"
    elif completed:
        outcome = "completed their check-in"
        if mood:
            mood_map = {
                "tough": "but it was tough",
                "good": "and felt good",
                "amazing": "and felt amazing",
            }
            outcome += f" ({mood_map.get(mood, '')})"
    else:
        outcome = "missed their check-in"
        if skip_reason:
            reason_map = {
                "work": "due to work",
                "tired": "because they were tired",
                "sick": "because they're sick",
                "schedule": "due to schedule conflicts",
                "other": "",
            }
            outcome += f" {reason_map.get(skip_reason, '')}"

    # Style instructions
    style_prompts = {
        "supportive": "Be warm and encouraging. Celebrate wins, be gentle with misses.",
        "tough_love": "Be direct and challenging. Push them, but don't be mean or discouraging.",
        "calm": "Be patient and philosophical. Focus on the long game and inner peace.",
    }

    # Build streak context
    streak_context = ""
    if current_streak > 0:
        streak_context = f"Current streak: {current_streak} days. "
        if longest_streak > current_streak:
            streak_context += f"Their longest streak is {longest_streak} days. "
            if current_streak >= longest_streak - 3:
                streak_context += "They're close to beating their record! "
        elif current_streak == longest_streak:
            streak_context += "This is their longest streak ever! "

    try:
        system_prompt = f"""You are the user's personal accountability coach in the FitNudge app.

Style: {style_prompts.get(motivation_style, style_prompts["supportive"])}

Generate a SHORT, personalized response (2-3 sentences, ~40 words max).

Context:
- User: {user_name}
- Goal: {goal_title}
- Outcome: {outcome}
- {streak_context}
- Their "why": {why_statement or "not specified"}

Rules:
- Address them by name
- Reference their specific goal
- If streak is notable (7+, 14+, 30+), mention it
- If they're close to their longest streak, mention it
- If they missed, reference their "why" to remind them
- Be specific, not generic
- No emojis in the response
- Keep it conversational and genuine"""

        response = await client.chat.completions.create(
            model="gpt-4o-mini",  # Cost-effective model
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": "Generate the personalized response."},
            ],
            max_tokens=80,
            temperature=0.8,
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        logger.error(f"Failed to generate AI check-in response: {e}")
        # Fall back to template
        return get_template_response(
            user_name=user_name,
            completed=completed,
            is_rest_day=is_rest_day,
            current_streak=current_streak,
            motivation_style=motivation_style,
        )


# =============================================================================
# DAILY MOTIVATIONS (Morning messages)
# =============================================================================


async def generate_daily_motivation(
    user_name: str,
    motivation_style: str = "supportive",
    current_streaks: Optional[List[dict]] = None,
    goals: Optional[List[dict]] = None,
) -> dict:
    """
    Generate daily motivation message for MotivationCard.

    Returns:
        {
            "message": "...",
            "background_style": "gradient_sunset",
            "background_colors": ["#FF9A9E", "#FECFEF", "#FECFEF"]
        }
    """
    # Build context
    context_parts = []
    if goals:
        goal_names = [g.get("title", "") for g in goals[:3]]
        if goal_names:
            context_parts.append(f"Active goals: {', '.join(goal_names)}")

    if current_streaks:
        best_streak = max(
            (s.get("current_streak", 0) for s in current_streaks), default=0
        )
        if best_streak > 0:
            context_parts.append(f"Current best streak: {best_streak} days")

    context = (
        "\n".join(context_parts) if context_parts else "New user, just getting started"
    )

    # Style mapping
    style_prompts = {
        "supportive": "Warm, encouraging, celebrates every small win. Use gentle language.",
        "tough_love": "Direct, challenging, pushes them to be better. No excuses tolerated.",
        "calm": "Patient, balanced, philosophical. Focus on the journey, not the destination.",
    }

    style_instruction = style_prompts.get(motivation_style, style_prompts["supportive"])

    try:
        response = await client.chat.completions.create(
            model="gpt-4o-mini",  # Cost-effective for daily motivations
            messages=[
                {
                    "role": "system",
                    "content": f"""You are a personal accountability coach named FitNudge.
Generate a SHORT daily motivation message (2-3 sentences max, ~50 words).

Style: {style_instruction}

Rules:
- Address the user by name ({user_name})
- Reference their goals/progress if provided
- Be specific, not generic
- End with energy and action
- No hashtags or emojis in the message itself
- Make it feel personal and genuine
- DO NOT use time-specific greetings like "Good morning", "Rise and shine", etc.
  (The user may see this at any time of day)""",
                },
                {
                    "role": "user",
                    "content": f"Generate a daily motivation for today.\n\nUser context:\n{context}",
                },
            ],
            max_tokens=100,
            temperature=0.9,  # Higher creativity for variety
        )

        message = response.choices[0].message.content.strip()

    except Exception as e:
        logger.error(f"Failed to generate daily motivation: {e}")
        # Fallback messages by style (time-neutral - no "good morning" etc.)
        fallbacks = {
            "supportive": f"Hey {user_name}! Today is full of possibilities. Every small step counts. Let's make it a great day!",
            "tough_love": f"Let's go, {user_name}. Yesterday's excuses won't build tomorrow's success. Time to show up.",
            "calm": f"A fresh start, {user_name}. Remember why you started. Progress happens one moment at a time.",
        }
        message = fallbacks.get(motivation_style, fallbacks["supportive"])

    # Randomly select background style
    styles = list(BACKGROUND_COLORS.keys())
    background_style = random.choice(styles)

    return {
        "message": message,
        "background_style": background_style,
        "background_colors": BACKGROUND_COLORS[background_style],
    }


def get_colors_for_style(style: str) -> List[str]:
    """Get gradient colors for a background style."""
    return BACKGROUND_COLORS.get(style, BACKGROUND_COLORS["gradient_sunset"])
