"""
FitNudge V2 - Daily Motivations API

Endpoints for the MotivationCard on the home screen.
Daily motivations are generated by Celery scheduler each morning.

V2 Table: daily_motivations
- message: The AI-generated motivation text
- background_style: Gradient style name
- background_colors: Array of hex colors for gradient
- date: One motivation per user per day
- share_count: Track social shares
"""

from fastapi import APIRouter, HTTPException, status, Depends, Query
from pydantic import BaseModel
from typing import List, Optional
from datetime import date, datetime
from app.core.flexible_auth import get_current_user
from app.services.logger import logger

router = APIRouter(redirect_slashes=False)


# =============================================================================
# PYDANTIC MODELS
# =============================================================================


class DailyMotivationResponse(BaseModel):
    """Response model for daily motivations."""

    id: str
    user_id: str
    message: str
    background_style: str
    background_colors: Optional[List[str]] = None
    date: str
    generated_at: Optional[str] = None
    share_count: int = 0
    sent_at: Optional[str] = None
    created_at: str


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def _get_colors_for_style(style: str) -> List[str]:
    """Get gradient colors for a background style."""
    from app.services.motivation_service import get_colors_for_style

    return get_colors_for_style(style)


# =============================================================================
# ENDPOINTS
# =============================================================================


def _get_user_today(timezone: str) -> date:
    """Get today's date in user's timezone."""
    import pytz

    try:
        user_tz = pytz.timezone(timezone or "UTC")
        return datetime.now(user_tz).date()
    except Exception:
        return date.today()


def _was_generated_today_utc(generated_at: str | None) -> bool:
    """
    Check if generated_at falls within today in UTC.
    One motivation per UTC day — consistent regardless of user timezone.
    If generated_at is missing or invalid, returns False.
    """
    import pytz

    if not generated_at:
        return False
    try:
        # Parse generated_at (ISO format, may or may not have TZ)
        dt = datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = pytz.UTC.localize(dt)
        gen_date_utc = dt.astimezone(pytz.UTC).date()
        today_utc = datetime.now(pytz.UTC).date()
        return gen_date_utc == today_utc
    except Exception:
        return False


def _get_goals_scheduled_today(
    user_id: str, today: date, supabase
) -> list:
    """
    Get goals scheduled for check-in today (same logic as home.py).
    Returns list of goal dicts with title, current_streak, etc.
    """
    goals_result = (
        supabase.table("goals")
        .select("id, title, current_streak, frequency_type, target_days, last_checkin_date")
        .eq("user_id", user_id)
        .eq("status", "active")
        .execute()
    )
    active_goals = goals_result.data or []
    today_str = today.isoformat()
    today_day_of_week = today.weekday()  # 0=Monday, 6=Sunday

    scheduled_today = []
    for goal in active_goals:
        is_scheduled = False
        frequency_type = goal.get("frequency_type", "daily")
        target_days = goal.get("target_days", [])

        if frequency_type == "daily":
            is_scheduled = True
        elif frequency_type == "weekly" and target_days:
            today_day_adjusted = (today_day_of_week + 1) % 7
            is_scheduled = today_day_adjusted in target_days

        if not is_scheduled:
            continue
        if goal.get("last_checkin_date") == today_str:
            continue

        scheduled_today.append(goal)

    return scheduled_today


@router.get("/today", response_model=DailyMotivationResponse)
async def get_today_motivation(
    current_user: dict = Depends(get_current_user),
    timezone: str = Query("UTC", description="User's timezone"),
):
    """
    Get today's daily motivation for the user.

    If no motivation exists for today (in user's timezone), or if the stored
    motivation is not for today, delete it and generate a new one.
    Focus: motivation is for goals scheduled for check-in today; if none, general.
    """
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()
    user_id = current_user["id"]
    user_today = _get_user_today(timezone)
    today_str = user_today.isoformat()

    # Try to get today's motivation
    result = (
        supabase.table("daily_motivations")
        .select("*")
        .eq("user_id", user_id)
        .eq("date", today_str)
        .limit(1)
        .execute()
    )

    if result and result.data and len(result.data) > 0:
        motivation = result.data[0]
        # Validate: was it generated today in UTC? (one motivation per UTC day, consistent for all timezones)
        if not _was_generated_today_utc(motivation.get("generated_at")):
            supabase.table("daily_motivations").delete().eq("id", motivation["id"]).execute()
        else:
            if not motivation.get("background_colors"):
                motivation["background_colors"] = _get_colors_for_style(
                    motivation.get("background_style", "gradient_sunset")
                )
            return motivation

    # No valid motivation for today - generate one on-the-fly
    try:
        from app.services.motivation_service import generate_daily_motivation

        goals_scheduled_today = _get_goals_scheduled_today(user_id, user_today, supabase)

        motivation_data = await generate_daily_motivation(
            user_name=current_user.get("name", "there"),
            motivation_style=current_user.get("motivation_style", "supportive"),
            goals_scheduled_today=goals_scheduled_today,
        )

        # Delete ALL existing motivations for this user
        supabase.table("daily_motivations").delete().eq("user_id", user_id).execute()

        new_motivation = {
            "user_id": user_id,
            "message": motivation_data["message"],
            "background_style": motivation_data["background_style"],
            "background_colors": motivation_data["background_colors"],
            "date": today_str,
            "generated_at": datetime.utcnow().isoformat(),
        }

        insert_result = (
            supabase.table("daily_motivations").insert(new_motivation).execute()
        )

        if insert_result.data:
            return insert_result.data[0]

    except Exception as e:
        logger.error(f"Failed to generate daily motivation: {e}")

    fallback = {
        "id": "fallback",
        "user_id": user_id,
        "message": f"Hey {current_user.get('name', 'there')}! Today is full of possibilities. Make it count!",
        "background_style": "gradient_sunset",
        "background_colors": ["#FF9A9E", "#FECFEF", "#FECFEF"],
        "date": today_str,
        "generated_at": datetime.utcnow().isoformat(),
        "share_count": 0,
        "sent_at": None,
        "created_at": datetime.utcnow().isoformat(),
    }
    return fallback


@router.get("/", response_model=List[DailyMotivationResponse])
async def get_motivations(
    current_user: dict = Depends(get_current_user),
    limit: int = Query(30, ge=1, le=100),
    offset: int = Query(0, ge=0),
):
    """Get user's daily motivation history."""
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()

    result = (
        supabase.table("daily_motivations")
        .select("*")
        .eq("user_id", current_user["id"])
        .order("date", desc=True)
        .range(offset, offset + limit - 1)
        .execute()
    )

    # Add background_colors if missing
    motivations = result.data or []
    for motivation in motivations:
        if not motivation.get("background_colors"):
            motivation["background_colors"] = _get_colors_for_style(
                motivation.get("background_style", "gradient_sunset")
            )

    return motivations


@router.get("/{motivation_id}", response_model=DailyMotivationResponse)
async def get_motivation(
    motivation_id: str,
    current_user: dict = Depends(get_current_user),
):
    """Get a specific daily motivation by ID."""
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()

    result = (
        supabase.table("daily_motivations")
        .select("*")
        .eq("id", motivation_id)
        .eq("user_id", current_user["id"])
        .limit(1)
        .execute()
    )

    if not result or not result.data or len(result.data) == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Motivation not found"
        )

    motivation = result.data[0]
    if not motivation.get("background_colors"):
        motivation["background_colors"] = _get_colors_for_style(
            motivation.get("background_style", "gradient_sunset")
        )

    return motivation


@router.post("/{motivation_id}/share")
async def share_motivation(
    motivation_id: str,
    current_user: dict = Depends(get_current_user),
):
    """Increment share count for a motivation."""
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()

    # Verify ownership
    motivation = (
        supabase.table("daily_motivations")
        .select("share_count")
        .eq("id", motivation_id)
        .eq("user_id", current_user["id"])
        .limit(1)
        .execute()
    )

    if not motivation or not motivation.data or len(motivation.data) == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Motivation not found"
        )

    current_count = motivation.data[0].get("share_count", 0)

    supabase.table("daily_motivations").update({"share_count": current_count + 1}).eq(
        "id", motivation_id
    ).execute()

    return {"share_count": current_count + 1}


@router.post("/regenerate", response_model=DailyMotivationResponse)
async def regenerate_motivation(
    current_user: dict = Depends(get_current_user),
    timezone: str = Query("UTC", description="User's timezone"),
):
    """
    Regenerate today's daily motivation (Premium only).
    Uses same goal-focused logic as get_today.
    """
    from app.core.database import get_supabase_client
    from app.core.subscriptions import get_user_effective_plan
    from app.services.motivation_service import generate_daily_motivation

    supabase = get_supabase_client()
    user_id = current_user["id"]
    user_today = _get_user_today(timezone)
    today_str = user_today.isoformat()

    plan = get_user_effective_plan(user_id, supabase=supabase)
    if plan != "premium":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Premium subscription required",
        )

    goals_scheduled_today = _get_goals_scheduled_today(user_id, user_today, supabase)

    motivation_data = await generate_daily_motivation(
        user_name=current_user.get("name", "there"),
        motivation_style=current_user.get("motivation_style", "supportive"),
        goals_scheduled_today=goals_scheduled_today,
    )

    supabase.table("daily_motivations").delete().eq("user_id", user_id).execute()

    result = (
        supabase.table("daily_motivations")
        .insert(
            {
                "user_id": user_id,
                "message": motivation_data["message"],
                "background_style": motivation_data["background_style"],
                "background_colors": motivation_data["background_colors"],
                "date": today_str,
                "generated_at": datetime.utcnow().isoformat(),
            }
        )
        .execute()
    )

    if not result.data:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to regenerate motivation",
        )

    return result.data[0]
