"""
FitNudge V2 - Daily Motivations API

Endpoints for the MotivationCard on the home screen.
Daily motivations are generated by Celery scheduler each morning.

V2 Table: daily_motivations
- message: The AI-generated motivation text
- background_style: Gradient style name
- background_colors: Array of hex colors for gradient
- date: One motivation per user per day
- share_count: Track social shares
"""

from fastapi import APIRouter, HTTPException, status, Depends, Query
from pydantic import BaseModel
from typing import List, Optional
from datetime import date, datetime
from app.core.flexible_auth import get_current_user
from app.services.logger import logger

router = APIRouter(redirect_slashes=False)


# =============================================================================
# PYDANTIC MODELS
# =============================================================================


class DailyMotivationResponse(BaseModel):
    """Response model for daily motivations."""

    id: str
    user_id: str
    message: str
    background_style: str
    background_colors: Optional[List[str]] = None
    date: str
    generated_at: Optional[str] = None
    share_count: int = 0
    sent_at: Optional[str] = None
    created_at: str


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def _get_colors_for_style(style: str) -> List[str]:
    """Get gradient colors for a background style."""
    from app.services.motivation_service import get_colors_for_style

    return get_colors_for_style(style)


# =============================================================================
# ENDPOINTS
# =============================================================================


@router.get("/today", response_model=DailyMotivationResponse)
async def get_today_motivation(current_user: dict = Depends(get_current_user)):
    """
    Get today's daily motivation for the user.

    If no motivation exists for today, generate one on-the-fly.
    (Normally Celery generates these in the morning via scheduled task)
    """
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()
    user_id = current_user["id"]
    today = date.today().isoformat()

    # Try to get today's motivation
    result = (
        supabase.table("daily_motivations")
        .select("*")
        .eq("user_id", user_id)
        .eq("date", today)
        .limit(1)
        .execute()
    )

    if result and result.data and len(result.data) > 0:
        motivation = result.data[0]
        # Add background_colors if not present
        if not motivation.get("background_colors"):
            motivation["background_colors"] = _get_colors_for_style(
                motivation.get("background_style", "gradient_sunset")
            )
        return motivation

    # No motivation for today - generate one on-the-fly
    try:
        from app.services.motivation_service import generate_daily_motivation

        # Get user's goals for context
        goals = (
            supabase.table("goals")
            .select("title, current_streak")
            .eq("user_id", user_id)
            .eq("status", "active")
            .limit(3)
            .execute()
        )

        motivation_data = await generate_daily_motivation(
            user_name=current_user.get("name", "there"),
            motivation_style=current_user.get("motivation_style", "supportive"),
            current_streaks=goals.data if goals.data else None,
            goals=goals.data if goals.data else None,
        )

        # Delete ALL existing motivations for this user (only one at a time)
        supabase.table("daily_motivations").delete().eq("user_id", user_id).execute()

        # Save new motivation to database
        new_motivation = {
            "user_id": user_id,
            "message": motivation_data["message"],
            "background_style": motivation_data["background_style"],
            "background_colors": motivation_data["background_colors"],
            "date": today,
            "generated_at": datetime.utcnow().isoformat(),
        }

        insert_result = (
            supabase.table("daily_motivations").insert(new_motivation).execute()
        )

        if insert_result.data:
            return insert_result.data[0]

    except Exception as e:
        logger.error(f"Failed to generate daily motivation: {e}")

    # Return a fallback (time-neutral - no "good morning" etc.)
    fallback = {
        "id": "fallback",
        "user_id": user_id,
        "message": f"Hey {current_user.get('name', 'there')}! Today is full of possibilities. Make it count!",
        "background_style": "gradient_sunset",
        "background_colors": ["#FF9A9E", "#FECFEF", "#FECFEF"],
        "date": today,
        "generated_at": datetime.utcnow().isoformat(),
        "share_count": 0,
        "sent_at": None,
        "created_at": datetime.utcnow().isoformat(),
    }
    return fallback


@router.get("/", response_model=List[DailyMotivationResponse])
async def get_motivations(
    current_user: dict = Depends(get_current_user),
    limit: int = Query(30, ge=1, le=100),
    offset: int = Query(0, ge=0),
):
    """Get user's daily motivation history."""
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()

    result = (
        supabase.table("daily_motivations")
        .select("*")
        .eq("user_id", current_user["id"])
        .order("date", desc=True)
        .range(offset, offset + limit - 1)
        .execute()
    )

    # Add background_colors if missing
    motivations = result.data or []
    for motivation in motivations:
        if not motivation.get("background_colors"):
            motivation["background_colors"] = _get_colors_for_style(
                motivation.get("background_style", "gradient_sunset")
            )

    return motivations


@router.get("/{motivation_id}", response_model=DailyMotivationResponse)
async def get_motivation(
    motivation_id: str,
    current_user: dict = Depends(get_current_user),
):
    """Get a specific daily motivation by ID."""
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()

    result = (
        supabase.table("daily_motivations")
        .select("*")
        .eq("id", motivation_id)
        .eq("user_id", current_user["id"])
        .limit(1)
        .execute()
    )

    if not result or not result.data or len(result.data) == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Motivation not found"
        )

    motivation = result.data[0]
    if not motivation.get("background_colors"):
        motivation["background_colors"] = _get_colors_for_style(
            motivation.get("background_style", "gradient_sunset")
        )

    return motivation


@router.post("/{motivation_id}/share")
async def share_motivation(
    motivation_id: str,
    current_user: dict = Depends(get_current_user),
):
    """Increment share count for a motivation."""
    from app.core.database import get_supabase_client

    supabase = get_supabase_client()

    # Verify ownership
    motivation = (
        supabase.table("daily_motivations")
        .select("share_count")
        .eq("id", motivation_id)
        .eq("user_id", current_user["id"])
        .limit(1)
        .execute()
    )

    if not motivation or not motivation.data or len(motivation.data) == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Motivation not found"
        )

    current_count = motivation.data[0].get("share_count", 0)

    supabase.table("daily_motivations").update({"share_count": current_count + 1}).eq(
        "id", motivation_id
    ).execute()

    return {"share_count": current_count + 1}


@router.post("/regenerate", response_model=DailyMotivationResponse)
async def regenerate_motivation(current_user: dict = Depends(get_current_user)):
    """
    Regenerate today's daily motivation.

    This allows users to get a new motivation if they don't like the current one.
    Could be limited to premium users or rate-limited.
    """
    from app.core.database import get_supabase_client
    from app.services.motivation_service import generate_daily_motivation

    supabase = get_supabase_client()
    user_id = current_user["id"]
    today = date.today().isoformat()

    # Get user's goals for context
    goals = (
        supabase.table("goals")
        .select("title, current_streak")
        .eq("user_id", user_id)
        .eq("status", "active")
        .limit(3)
        .execute()
    )

    motivation_data = await generate_daily_motivation(
        user_name=current_user.get("name", "there"),
        motivation_style=current_user.get("motivation_style", "supportive"),
        current_streaks=goals.data if goals.data else None,
        goals=goals.data if goals.data else None,
    )

    # Delete ALL existing motivations for this user (only one at a time)
    supabase.table("daily_motivations").delete().eq("user_id", user_id).execute()

    # Insert new motivation
    result = (
        supabase.table("daily_motivations")
        .insert(
            {
                "user_id": user_id,
                "message": motivation_data["message"],
                "background_style": motivation_data["background_style"],
                "background_colors": motivation_data["background_colors"],
                "date": today,
                "generated_at": datetime.utcnow().isoformat(),
            }
        )
        .execute()
    )

    if not result.data:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to regenerate motivation",
        )

    return result.data[0]
